import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store.ts/provider";
import { Header } from "./components/header/header";
import { Footer } from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Providers>
        <Header/>
        <body className={inter.className}>
          <main>{children}</main>
        </body>
        <Footer/>
      </Providers>
    </html>
  );
}
